### ISSUE TITLE
Sort of milestone results is not idempotent

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/amo-milestones#7]
For the same set of data the same order of results should be shown.

Currently the data is "post-sorted" by username but it should also be sorted by a second criteria too so that we maintain consistent order within the same results.

**Comment by diox** [comment]
Ideally sorting by closed date would be nice, so it would roughly correspond to the order in which things were done (or at least, merged)

**Comment by muffinresearch** [comment]
@diox would modified generally work for that so it's one criteria that would work across both open and closed issues?

**Comment by muffinresearch** [comment]
Could probably use closed_at if present and otherwise fall-back to updated_at.

**Comment by muffinresearch** [comment]
This is deployed, it now sorts by:

- Assignee name
- open or closed (closed first)
- closed date or updated date (oldest first)
